name: flutter_architecture_project
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^2.0.1
  # Bloc for state management
  flutter_bloc: ^3.2.0
  # Value equality
  equatable: ^0.4.0
  # Functional programming thingies
  dartz: ^0.8.6
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.3+4
  # This package provides internationalization and localization facilities,
  # including message translation, plurals and genders,
  # date/number formatting and parsing, and bidirectional text.
  intl: ^0.16.0
  path_provider: ^1.5.0
  # A Flutter plugin that provides a WebView widget.
  flutter_webview_plugin: ^0.3.9+1
  # Animatable bottom app bar with expandable sheet
  expandable_bottom_bar: ^0.1.1
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^1.0.1
  # A Flutter plugin for iOS and Android for playing back video on a Widget surface.
  video_player: ^0.10.9+2
  chewie: ^0.9.10

  page_transition: ^1.1.4
  # Work with JWT Token
  jwt_decode: ^0.1.0
  # A Flutter plugin to store data in secure storage
  flutter_secure_storage: ^3.3.1+1
  # Simple Animations is a package for Flutter to boost your animation productivity
  # by simplifying the way to create animations.
  simple_animations: ^1.3.6
  # A Flutter widget for rendering static html tags as Flutter widgets.
  flutter_html: ^0.8.2
  # Loading button with simple implementation
  rounded_loading_button: ^1.0.0
  # A carousel slider widget, support infinite scroll and custom child widget, with auto play feature.
  carousel_slider: ^1.4.1
  # Use this package if you need more customization when notifying your user. For Android developers,
  # it is made to substitute toasts and snackbars. IOS developers,
  # I don't know what you use there, but you will like it.
  dio: ^3.0.9
  connectivity: ^0.4.8+2
  pull_to_refresh: ^1.5.7
  flutter_easyrefresh: ^2.0.9
  flutter_datetime_picker: ^1.3.5
  # The best swiper for flutter , with multiple layouts, infinite loop. Compatible with Android & iOS.
  flutter_swiper: ^1.1.6
  # This package includes ReorderableSliverList, ReorderableTable, ReorderableWrap, ReorderableRow,
  # and ReorderableColumn, which are reorderable versions of Flutter's SliverList, Table, Wrap, Row, and Column respectively.
  reorderables: ^0.3.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/metInvestBackground.png
    - assets/images/metInvestIcon.png
    - assets/images/noPhoto.png
    - assets/images/video_test.jpg
    - assets/icons/change.png
    - assets/icons/applications.png
    - assets/icons/birthday.png
    - assets/icons/calendarEvents.png
    - assets/icons/negotiationReservation.png
    - assets/icons/news.png
    - assets/icons/phonebook.png
    - assets/icons/polls.png
    - assets/icons/profile.png
    - assets/icons/videoGallery.png
    - assets/icons/ÑorporateDocuments.png
    - assets/icons/newsHolding.png
    - assets/icons/newsCompany.png
    - assets/icons/home.png
    - assets/icons/iconDrag.png
    - assets/icons/archivePolls.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
